MVE.PatientPortal.API/MVE.PatientPortal.API/Controllers/PortalAdminController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVE.PatientPortal.API.Utilities;
using MVE.PatientPortal.API.Models;

namespace MVE.PatientPortal.API.Controllers
{
    [Authorize]
    public class PortalAdminController : Controller
    {
        public ActionResult Dashboard()
        {
            ViewBag.PracticeList = PortalAdmin.LoadPractices();
            return View();
        }

        public ActionResult Practice(string PracticeName, string PracticeToken)
        {
            ViewBag.SelectedPracticeAlias = PracticeName;
            ViewBag.SelectedPracticeToken = PracticeToken;
            ViewBag.PracticeList = PortalAdmin.LoadPractices();
            return View("Dashboard");
        }

        [HttpPost]
        public ActionResult DoctorRegistration(FormCollection FC)
        {
            string PracticeToken = FC["PracticeToken"].ToString();
            string PracticeAliasName = FC["PracticeName"].ToString();
            string DoctorFirstName = FC["DoctorFirstName"].ToString();
            string DoctorLastName = FC["DoctorLastName"].ToString();
            string DoctorExternalId = FC["DoctorExternalId"].ToString();
            string DoctorAliasName = FC["DoctorAliasName"].ToString();
            string LocationExternalId = FC["LocationExternalId"].ToString();

            Doctor objDoctor = new Doctor()
            {
                AliasName = DoctorAliasName,
                ExternalId = DoctorExternalId,
                FirstName = DoctorFirstName,
                LastName = DoctorLastName,
                PracticeToken = PracticeToken,
                LocationExternalId = LocationExternalId
            };

            string RegistartionStatus = PortalAdmin.RegisterDoctor(objDoctor);

            if (RegistartionStatus == "Success")
            {
                ViewBag.Message = "Registration successfully completed";
                ViewBag.regStatus = "1";
            }
            else 
            {
                ViewBag.Message = "There is some issue, Please try after some time";
                ViewBag.regStatus = "0";
            }
            ViewBag.SelectedPracticeAlias = PracticeAliasName;
            ViewBag.SelectedPracticeToken = PracticeToken;
            ViewBag.PracticeList = PortalAdmin.LoadPractices();
            return View("Dashboard");
        }

    }
}

MVE.PatientPortal.API/MVE.PatientPortal.API/Views/PortalAdmin/Dashboard.cshtml
@{
    ViewBag.Title = "Portal Admin";
    Layout = null;
}
<div style="width:100%;display:inline-block;height:auto;">
    <div style="width:15%;display:inline-block;padding-left:1%;height:650px;background-color:#f1f1f1;">
        <h3 style="color:maroon">Portal Admin</h3>
        <div style="width:100%;height:600px;background-color:#f1f1f1;overflow-y:scroll">
            <table style="width:100%;max-height:600px;">
                @if (ViewBag.PracticeList != null)
                {
                    foreach (MVE.PatientPortal.API.Models.Practice Pc in ViewBag.PracticeList)
                    {
                        <tr>
                            <td style="padding:4px 2px;margin:0px 2px;border-bottom:black 1px solid;">
                                <a href=@Url.Action("Practice", new { PracticeName = @Pc.PracticeAlias, PracticeToken = @Pc.PracticeToken }) style="color: black; text-decoration: none;">@Pc.PracticeAlias</a>
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>
    <div style="width: 75%; display: inline-block; height: 650px; position: relative; top: -624px; margin-left: 2%;">
        @if (@ViewBag.regStatus == "1")
        {
            <script type="text/javascript">
                alert('@ViewBag.Message');
            </script>
        }

        @if (@ViewBag.SelectedPracticeAlias != null)
        {
            <h3 style="color:maroon;">@ViewBag.SelectedPracticeAlias</h3>
            using (@Html.BeginForm("DoctorRegistration", "PortalAdmin", FormMethod.Post))
            {
                <table>
                    <tr>
                        <td>
                            <h3>Doctor Registration</h3>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                    <tr style="display:none;">
                        <td>
                            Practice Token
                            <br />
                            <input type="text" name="PracticeToken" value=@ViewBag.SelectedPracticeToken readonly maxlength="100" style="width:500px;" />
                            <br /><br />
                        </td>
                    </tr>
                    <tr style="display:none;">
                        <td>
                            Practice Name
                            <br />
                            <input type="text" name="PracticeName" value=@ViewBag.SelectedPracticeAlias readonly maxlength="100" style="width:500px;" />
                            <br /><br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            First Name
                            <br />
                            <input type="text" name="DoctorFirstName" value="" maxlength="100" style="width:500px;" />
                            <br /><br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Last Name
                            <br />
                            <input type="text" name="DoctorLastName" value="" maxlength="100" style="width:500px;" />
                            <br /><br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            External Id
                            <br />
                            <input type="text" name="DoctorExternalId" value="" maxlength="100" style="width:500px;" />
                            <br /><br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Alias Name
                            <br />
                            <input type="text" name="DoctorAliasName" value="" maxlength="100" style="width:500px;" />
                            <br /><br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Location External Id
                            <br />
                            <input type="text" name="LocationExternalId" value="" maxlength="100" style="width:500px;" />
                            <br /><br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" value="Register" />
                        </td>
                    </tr>
                </table>
            }
        }
    </div>
</div>